if(NOT DEFINED SOURCE_DIR OR NOT DEFINED BINARY_DIR)
  message(FATAL_ERROR "SOURCE_DIR and BINARY_DIR are required")
endif()
set(installed_policy "${BINARY_DIR}/install/bin/rll-policy")
if(NOT EXISTS "${installed_policy}")
  message(FATAL_ERROR "native policy executable is not installed at ${installed_policy}")
endif()
execute_process(COMMAND "${installed_policy}" --help RESULT_VARIABLE help_result OUTPUT_QUIET ERROR_QUIET)
if(NOT help_result EQUAL 0)
  message(FATAL_ERROR "installed rll-policy --help failed: ${help_result}")
endif()
file(READ "${SOURCE_DIR}/../pyproject.toml" pyproject)
if(pyproject MATCHES "rll-policy[ \t]*=")
  message(FATAL_ERROR "pyproject.toml still registers a Python rll-policy command")
endif()
foreach(command IN ITEMS "rll-sim-hardware =" "rll-dummy-control =")
  if(NOT pyproject MATCHES "${command}")
    message(FATAL_ERROR "pyproject.toml lost the required Python command: ${command}")
  endif()
endforeach()
